const timezones = [
	{ country: "Portugal", timezone: "Europe/Lisbon", flag: "🇵🇹" },
	{ country: "Portugal (Azores)", timezone: "Atlantic/Azores", flag: "🇵🇹" },
	{ country: "United States", timezone: "America/New_York", flag: "🇺🇸" },
	{ country: "Brazil", timezone: "America/Sao_Paulo", flag: "🇧🇷" },
	{ country: "Japan", timezone: "Asia/Tokyo", flag: "🇯🇵" },
	{ country: "Australia", timezone: "Australia/Sydney", flag: "🇦🇺" },
	{ country: "India", timezone: "Asia/Kolkata", flag: "🇮🇳" },
	{ country: "Russia", timezone: "Europe/Moscow", flag: "🇷🇺" },
	{ country: "Germany", timezone: "Europe/Berlin", flag: "🇩🇪" },
	{ country: "South Africa", timezone: "Africa/Johannesburg", flag: "🇿🇦" },
	{ country: "Mexico", timezone: "America/Mexico_City", flag: "🇲🇽" },
	{ country: "Canada", timezone: "America/Toronto", flag: "🇨🇦" },
	{ country: "China", timezone: "Asia/Shanghai", flag: "🇨🇳" },
	{ country: "Argentina", timezone: "America/Argentina/Buenos_Aires", flag: "🇦🇷" },
	{ country: "Egypt", timezone: "Africa/Cairo", flag: "🇪🇬" },
	{ country: "France", timezone: "Europe/Paris", flag: "🇫🇷" },
	{ country: "United Kingdom", timezone: "Europe/London", flag: "🇬🇧" },
	{ country: "South Korea", timezone: "Asia/Seoul", flag: "🇰🇷" },
	{ country: "Saudi Arabia", timezone: "Asia/Riyadh", flag: "🇸🇦" },
	{ country: "New Zealand", timezone: "Pacific/Auckland", flag: "🇳🇿" },
	{ country: "Indonesia", timezone: "Asia/Jakarta", flag: "🇮🇩" },
	{ country: "Italy", timezone: "Europe/Rome", flag: "🇮🇹" },
	{ country: "Turkey", timezone: "Europe/Istanbul", flag: "🇹🇷" },
	{ country: "Colombia", timezone: "America/Bogota", flag: "🇨🇴" },
	{ country: "Chile", timezone: "America/Santiago", flag: "🇨🇱" },
	{ country: "Netherlands", timezone: "Europe/Amsterdam", flag: "🇳🇱" },
	{ country: "Sweden", timezone: "Europe/Stockholm", flag: "🇸🇪" },
	{ country: "Norway", timezone: "Europe/Oslo", flag: "🇳🇴" },
	{ country: "Thailand", timezone: "Asia/Bangkok", flag: "🇹🇭" },
	{ country: "Vietnam", timezone: "Asia/Ho_Chi_Minh", flag: "🇻🇳" },
	{ country: "Philippines", timezone: "Asia/Manila", flag: "🇵🇭" },
	{ country: "Greece", timezone: "Europe/Athens", flag: "🇬🇷" },
	{ country: "Poland", timezone: "Europe/Warsaw", flag: "🇵🇱" },
	{ country: "Czech Republic", timezone: "Europe/Prague", flag: "🇨🇿" },
	{ country: "Hungary", timezone: "Europe/Budapest", flag: "🇭🇺" },
	{ country: "Finland", timezone: "Europe/Helsinki", flag: "🇫🇮" },
	{ country: "Iceland", timezone: "Atlantic/Reykjavik", flag: "🇮🇸" },
	{ country: "Ireland", timezone: "Europe/Dublin", flag: "🇮🇪" },
	{ country: "Morocco", timezone: "Africa/Casablanca", flag: "🇲🇦" },
	{ country: "Kenya", timezone: "Africa/Nairobi", flag: "🇰🇪" },
	{ country: "Nigeria", timezone: "Africa/Lagos", flag: "🇳🇬" },
	{ country: "United Arab Emirates", timezone: "Asia/Dubai", flag: "🇦🇪" },
	{ country: "Qatar", timezone: "Asia/Qatar", flag: "🇶🇦" },
	{ country: "Singapore", timezone: "Asia/Singapore", flag: "🇸🇬" },
	{ country: "Malaysia", timezone: "Asia/Kuala_Lumpur", flag: "🇲🇾" },
	{ country: "Bangladesh", timezone: "Asia/Dhaka", flag: "🇧🇩" },
	{ country: "Pakistan", timezone: "Asia/Karachi", flag: "🇵🇰" },
	{ country: "Nepal", timezone: "Asia/Kathmandu", flag: "🇳🇵" },
	{ country: "Sri Lanka", timezone: "Asia/Colombo", flag: "🇱🇰" },
	{ country: "Israel", timezone: "Asia/Jerusalem", flag: "🇮🇱" },
	{ country: "Jordan", timezone: "Asia/Amman", flag: "🇯🇴" },
	{ country: "Lebanon", timezone: "Asia/Beirut", flag: "🇱🇧" },
	{ country: "Ukraine", timezone: "Europe/Kiev", flag: "🇺🇦" },
	{ country: "Belarus", timezone: "Europe/Minsk", flag: "🇧🇾" },
	{ country: "Kazakhstan", timezone: "Asia/Almaty", flag: "🇰🇿" },
	{ country: "Uzbekistan", timezone: "Asia/Tashkent", flag: "🇺🇿" },
	{ country: "Vietnam", timezone: "Asia/Ho_Chi_Minh", flag: "🇻🇳" },
	{ country: "Peru", timezone: "America/Lima", flag: "🇵🇪" },
	{ country: "Venezuela", timezone: "America/Caracas", flag: "🇻🇪" },
	{ country: "Cuba", timezone: "America/Havana", flag: "🇨🇺" },
	{ country: "Honduras", timezone: "America/Tegucigalpa", flag: "🇭🇳" },
	{ country: "Costa Rica", timezone: "America/Costa_Rica", flag: "🇨🇷" },
	{ country: "Panama", timezone: "America/Panama", flag: "🇵🇦" },
	{ country: "Guatemala", timezone: "America/Guatemala", flag: "🇬🇹" },
	{ country: "Paraguay", timezone: "America/Asuncion", flag: "🇵🇾" },
	{ country: "Uruguay", timezone: "America/Montevideo", flag: "🇺🇾" },
	{ country: "Bolivia", timezone: "America/La_Paz", flag: "🇧🇴" },
];
